language: node_js
node_js:
  - "6.11.1"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
before_script:
  - npm run lint
  - npm test
  - SL=true npm test
  - npm build
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info
addons:
  sauce_connect: true
